name: Create PR for Non-Base Branch Push

on:
  push:
    branches-ignore:
      - 'main'  # ベースブランチ（変更する必要がある場合はこの値を変更してください）

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # 全てのコミット履歴を取得

    - name: Set GitHub Token
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

    - name: Create Pull Request
      run: |
        # ghコマンドを使用してPull Requestを作成
        gh pr create \
          --base main \  # ベースブランチ（変更する必要がある場合はこの値を変更してください）
          --head ${{ github.ref_name }} \
          --reviewer ${{ github.actor }} \  # Pushしたユーザー
          --title "PR from ${{ github.ref_name }}" \
          --body "Generated Pull Request based on recent changes in ${{ github.ref_name }} branch." \
          --repo ${{ github.repository }} \
          || echo "Pull request already exists or no changes between branches to create one."

